= New Project Questions


== Capabilities

=== Functional Suitability

---- 
*Functional completeness* - Degree to which the set of functions covers all the specified tasks and intended users' objectives.
*Functional correctness* - Degree to which a product or system provides accurate results when used by intended users.
*Functional appropriateness* - Degree to which the functions facilitate the accomplishment of specified tasks and objectives.
----

* Have we covered All the requirements
* Does it actually work (produce the right output)
* Does it actually solve the problem

=== Performance Efficiency

----
*Time behavior* - Degree to which the response time and throughput rates of a product or system, when performing its functions, meet requirements. +
*Resource utilization* - Degree to which the amounts and types of resources used by a product or system, when performing its functions, meet requirements. +
*Capacity* - Degree to which the maximum limits of a product or system parameter meet requirements.
----

* Will it respond fast enough
* Does it use a reasonable amount of resources (hosting cost)
* Does it fall within limits 
** total hosting cost
** hosting platform or runtime/framework limitations

=== Compatibility

----
*Co-existence* - Degree to which a product can perform its required functions efficiently while sharing a common environment and resources with other products, without detrimental impact on any other product.
*Interoperability* - Degree to which a system, product or component can exchange information with other products and mutually use the information that has been exchanged.
----

* Does this share hosting (compute/storage/network) with anything else
* Does it integrate with anything or does something else integrate with it
* Does it need to produce output in a specific format

=== Interaction Capability

----
*Operability* - Degree to which a product or system has attributes that make it easy to operate and control.
*User error protection* - Degree to which a system prevents users against operation errors.
----

* Is it easy to use 
** CICD workflows
** New dev onboarding
** Is there an effect on any other systems
* Think about any easy to cause consequences/can unsafe functionality be removed

=== Reliability

----
*Faultlessness* - Degree to which a system, product or component performs specified functions without fault under normal operation.
*Availability* - Degree to which a system, product or component is operational and accessible when required for use.
*Fault tolerance* - Degree to which a system, product or component operates as intended despite the presence of hardware or software faults.
*Recoverability* - Degree to which, in the event of an interruption or a failure, a product or system can recover the data directly affected and re-establish the desired state of the system.
----

* Can this crash under normal operations/expected error conditions
* Is this available enough
** Does this align with hosting platforms recommendations
** Think about geographic regions
* Is this fault tolerant
** Does this align with hosting platforms recommendations
** Can independent processes actually crash independently
* Can this recover sufficiently
** Region vs Zone
** Hot vs Cold vs Warm
** Follow hosting providers recs for safe data
** Make sure IaC can be run from scratch (even in a different hosting locations)
** Think about long term backups AND retention laws

=== Security

----
*Confidentiality* - Degree to which a product or system ensures that data are accessible only to those authorized to have access.
*Integrity* - Degree to which a system, product or component ensures that the state of its system and data are protected from unauthorized modification or deletion either by malicious action or computer error.
*Non-repudiation* - Degree to which actions or events can be proven to have taken place so that the events or actions cannot be repudiated later.
*Accountability* - Degree to which the actions of an entity can be traced uniquely to the entity.
*Authenticity* - Degree to which the identity of a subject or resource can be proved to be the one claimed.
*Resistance* - Degree to which the product or system sustains operations while under attack from a malicious actor.
----

* Does this do RBAC and follow "Least Priv"
* Does this audit sufficiently
* Are you following hosting providers guidelines for internet protection
* Are there any requirements around ciphers/algorithms/etc
* Is E2E encryption needed

=== Maintainability

----
*Modularity* - Degree to which a system or computer program is composed of discrete components such that a change to one component has minimal impact on other components.
*Reusability* - Degree to which a product can be used as an asset in more than one system, or in building other assets.
*Analysability* - Degree of effectiveness and efficiency with which it is possible to assess the impact on a product or system of an intended change to one or more of its parts, to diagnose a product for deficiencies or causes of failures, or to identify parts to be modified.
*Modifiability* - Degree to which a product or system can be effectively and efficiently modified without introducing defects or degrading existing product quality.
*Testability* - Degree of effectiveness and efficiency with which test criteria can be established for a system, product or component and tests can be performed to determine whether those criteria have been met.
----

* Is there value in this being used elsewhere
* Is this easy to inspect/debug/troubleshoot
* Is this easy to change/configure
* Is this easy to test/verify correctness

=== Flexibility

----
*Adaptability* - Degree to which a product or system can effectively and efficiently be adapted for or transferred to different hardware, software or other operational or usage environments.
*Scalability* - Degree to which a product can handle growing or shrinking workloads or to adapt its capacity to handle variability.
*Installability* - Degree of effectiveness and efficiency with which a product or system can be successfully installed and/or uninstalled in a specified environment.
*Replaceability* - Degree to which a product can replace another specified software product for the same purpose in the same environment.
----

* Do we care about moving this to other hosting platforms
* Does it need to scale up/down and/or in/out
* Is it easy to deploy



== Misc

* Changes take too long to make.
* When one area of the system is changed, other areas unexpectedly break.
* Team members get in each other’s way when applying changes.
* It takes too long for the system to start up.